EMBARGOS DE DECLARAÇÃO - INADMISSIBILIDADE, OBSCURIDADE OU OMISSÃO - PRETENDIDO REEXAME DA CAUSA CARÁTER INFRINGENTE - INOCORRÊNCIA DE CONTRADIÇÃO, OBSCURIDADE OU OMISSÃO REJEITADOS.
- Não se revelam admissíveis os embargos de declaração, quando a parte recorrente - a pretexto de esclarecer uma inexistente situação de obscuridade, omissão ou contradição - os usa com o objetivo de infringir o julgado e viabilizar, assim, um indevido reexame da causa.
Precedentes do processo.
A nulidade radical provocada pela conduta do magistrado que arbitrariamente nega, ao réu, o direito de formular reperguntas aos demais litisconsortes penais passivos, contamina, por efeito causal, todos os atos subseqüentes do processo, notadamente aqueles de índole probatória, como a inquirição de testemunhas arroladas pelo Ministério Público.
Precedentes do processo.
