language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - python install.py

script:
  - python test.py

notifications:
  email:
    recipients:
      - vinicius@open.inf.br
    on_success: change
    on_failure: always